### ISSUE TITLE
Multi-stage docker build

### ISSUE THREAD

**Issue by FloncDev** [FloncDev/exquisite-exoplanets#15]
Helps decreasing build time and the final image size

**Comment by iauu** [comment]
How does multi-stage work

**Comment by FloncDev** [comment]
You can have a builder image and a runtime image, the latter only containing the bare essentials to run the code.
Not a priority but I'm planning on doing it soon.

**Comment by iauu** [comment]
My main idea(I know of) was only make it so the part that is usually unchanged is on the top and other on the bottom so it could cache it, which that's as far as I knowledge

**Comment by FloncDev** [comment]
Current image is fine and what you said definitely helps with decreasing build times. Multi-stage helps further improve on that.

**Comment by iauu** [comment]
Ye, would be nice to know about, next time if we have opportunity, we should move `COPY src/ ./` from line 2 to the second last line

I forgot to change that and couldn't be brother to create a pull req just for that
