### ISSUE TITLE
Shop Endpoints

### ISSUE THREAD

**Issue by MilaDog** [FloncDev/exquisite-exoplanets#30]
Will be starting with creating the shop endpoints for the company.
This would also entail the ability to purchase from the shop.

This is here so that the team can see it is busy being done. Will be goiing with what is in the docs file. Anything added will be mentioned in here (or anything that would be required).

**Comment by MilaDog** [comment]
Will be starting with this

**Comment by MilaDog** [comment]
Created shop endpoints are uploaded. Made a PR that can be merged with the rest of the project so long (if need be).

**Comment by iauu** [comment]
GET /shop sort params should have a default value that is not None

**Comment by MilaDog** [comment]
> GET /shop sort params should have a default value that is not None

Fixed this.
