### ISSUE TITLE
Achievements endpoints

### ISSUE THREAD

**Issue by MilaDog** [FloncDev/exquisite-exoplanets#31]
Been doing some thinking on what the achievements could be.

There are the general achievements, like hitting a certain experience level, planet etc.
Another idea I had would be an achievement that the user can get for their company being the "top of the leaderboard" in terms of company worth. This is a bit tricky for company's starting out, so would only really occur after the company reaches a certain worth. From then on, there can be a basic achievement for reaching that certain worth, but **one** special achievement that can only be held by **one** company at a time for being the company with the most worth. This would, of course, bounce around between company's. 

THen something not really related to the achievements part, but the following would fall into the `information overload` section. When people are on the leader board, I think it would be cool to track how long a company has held the #1 position for. This can be easily added to their `company overview` command. Thoughts?

I was also thinking about a way to make new achievements on the fly. Seems like something nice to have, but may be out of scope for the project. Thoughts?

**Comment by bensgilbert** [comment]
I like this idea of achievements and a `#1 Position` seems like a cool idea :)
There should probably be a `/leaderboard` slash command to view the top `n` companies as well in that case

**Comment by iauu** [comment]
Sound nice, would this be in v3?

**Comment by MilaDog** [comment]
Most likely. Will be working on it. Would like the `api` branch to be approved first.

**Comment by MilaDog** [comment]
Starting with this
