### ISSUE TITLE
Game Design

### ISSUE THREAD

**Issue by FloncDev** [FloncDev/exquisite-exoplanets#7]

**Comment by Elektriman** [comment]
# Game design document
This document should explain in details
- how to play the game
- how to acquire points / "win"
- how to progress / level up
- the primary mechanics
- the secondary mechanics

**Comment by MilaDog** [comment]
Mentioned some stuff in the [lore section](https://github.com/FloncDev/exquisite-exoplanets/issues/11#issuecomment-2237489100)

**Comment by Elektriman** [comment]
#36 added the main classes. They are not finished yet. I need to make them interact with the database and I need to make the objects structure match the data tables (+ make the entity relationship graph)

**Comment by Elektriman** [comment]
we can now generate planets + the associated resources and collect resources. I need someone help to make the runtime and to link the frontend to the api
